website/models.py
from . import dataBase
from flask_login import UserMixin

# Database model for posts/cards that exist

class Cardpost(dataBase.Model, UserMixin):
    __tablename__ = 'cardpost'

    def __init__(self, business_name, business_bio, business_addy, business_photos, business_type):
        self.business_name = business_name
        self.business_bio = business_bio
        self.business_addy = business_addy
        self.business_photos = business_photos
        self.business_type = business_type

    business_id = dataBase.Column(dataBase.Integer, primary_key=True)
    business_name = dataBase.Column(dataBase.String(50), unique=True, nullable=False)
    business_bio = dataBase.Column(dataBase.String(150), nullable=False)
    business_addy = dataBase.Column(dataBase.String(50), nullable=False)
    business_photos = dataBase.Column(dataBase.String(50))
    business_type = dataBase.Column(dataBase.String(50), nullable=False)

    @classmethod
    def createMethod(self, business_name, business_bio, business_addy, business_photos, business_type):
        myCard = Cardpost()
        myCard.business_name = business_name
        myCard.business_bio = business_bio
        myCard.business_addy = business_addy
        myCard.business_photos = business_photos
        myCard.business_type = business_type

        dataBase.session.add(myCard)
        dataBase.session.commit()
        return myCard

website/__init__.py
from flask import Flask 
from flask_sqlalchemy import SQLAlchemy
from os import path


dataBase = SQLAlchemy()
DB_NAME = "database.db"

def create_app():
    """ base function for creating site"""

    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'kevinwasntmutedlol'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    dataBase.init_app(app)

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')

    from .models import Cardpost

    
    create_db(app)

    return app

def create_db(application):
    """ check to make sure the database exists. create if it is not."""
    if not path.exists('website/' + DB_NAME):
        dataBase.create_all(app=application)
        print('Database created')

website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
# from .models import Cardpost

from . import dataBase
import sqlite3

auth = Blueprint('auth', __name__)

@auth.route('/formspage', methods=['GET', 'POST'])
def forms():
    """ Function for our form, checks for proper input"""
    if request.method == 'POST':
        BusinessName = request.form.get('BusinessName')
        Bio = request.form.get('Bio')
        Address = request.form.get('Address')
        Photos = request.form.get('Photos')
        BusinessType = request.form.get('BusinessType')


        # add business name into the database
        if len(BusinessName) <= 0:
            flash('enter a business name', category='noData')
        elif len(Bio) <= 0:
            flash('say something to you clients!', category='noData')
        elif len(Address) <= 0:
            flash('enter the location of your business', category='noData')
        elif BusinessType == "Choose":
            flash('choose one of the business types', category = 'noData' )
        else:
            
            # Cardpost.createMethod(BusinessName, Bio, Address, Photos, 'errorhere')
            # kevin = sqlite3.connect('database.db')
            # sql_insert = "INSERT INTO Cardpost(BusinessName, Bio, Address, Photos, BusinessType) VALUES (%s, %s, %s, %s, %s)"
            # kevin.execute(sql_insert, Cardpost)
            # flash('Card succesfully made', category='success')
            # kevin.close()
            # new_post = Cardpost(business_name=BusinessName, business_bio=Bio, business_addy=Address, business_photos=Photos, business_type=BusinessType)
            # dataBase.session.add(new_post)
            # dataBase.session.commit()
            flash('Card succesfully made', category='success')
            return redirect(url_for('views.home'))


    return render_template("form.html", boolean=True)


@auth.route('/aboutUs')
def aboutUs():
    """Function for"""
    return render_template("aboutus.html", boolean=True)

@auth.route('/gallery')
def gallery():
    """Function for"""
    return render_template("index.html", boolean=True)

website/views.py
from flask import Blueprint, render_template
views = Blueprint('views', __name__)

# add URL to homepage
@views.route('/') 
def home():
    return render_template("index.html", boolean=True)

website/templates/aboutus.html
<html>
    <head>
        <meta name="viewport" content="width=device-width", intital-scale=1.0>
        <title>bro idek</title>

        <link rel = "stylesheet" href="../static/styles/aboutstyle.css">

        <link href="https://fonts.googleapis.com/css?family=Roboto:wght@400;700&display=swap" rel = "stylesheet">
    </head>
    <body>
        <div class = "container">
            <div class = "navbar">
                <img src="../static/styles/logo.jpeg" class ="logo"> <!-- We add our logo here when we make it -->
                <nav>
                    <ul>
                        <li><a href="{{ url_for('auth.gallery') }}">GALLERY</a></li>
                        <li><a href="{{ url_for('auth.aboutUs') }}">ABOUT US</a></li>
                    </ul>
                </nav>
                <img src = "../static/styles/menu.png" class ="menu-icon"> <!-- Menu Icon is needed -->
            </div>
    
            <div class ="row">
                <div class = "col">
                    <h1 class="title">SB Gallery</h1>
                    <p>Hey! Take a sneak peak at our dev team!</p>
                </div>
                
                <div class="bioLeft">
                    <img src="../static/styles/mao.jpg" class="kev"> 
                </div>
                <div class = "kevbio">
                    <h2> Kevin Shao </h2>
                    <p2> I am a first year CS student at Ryerson University!<br>I enjoy video editing and crying about my code not working :D <br> Here is my cat named Mao! (litterally cat in chinese)</p2>
                </div>

                <div class="bioRight">
                    <img src="../static/styles/ky.jpg" class="ky">
                </div>
                <div class = "kybio">
                    <h2> Kyron Trinh </h2>
                    <p2> Hola, as you can see my name is Kyron<br>I’m currently a student at Ryerson University for Computer Science <br> I love volleyball and basketball and from my picture, my doggo Gucci!</p2>
                </div>
                <div class="bioLeft">
                    <img src="../static/styles/anna.jpg" class="anna">
                </div>
                <div class = "annabio">
                    <h2> Annabel Chao </h2>
                    <p2> Me anna<br>here is my cat neko san</p2>
                </div>

                <div class="bioRight">
                    <img src="../static/styles/bun.jpg" class="amy">
                </div>
                <div class = "amybio">
                    <h2> Amy Xie </h2>
                    <p2> Hola, as you can see my name is Kyron<br>I’m currently a student at Ryerson University for Computer Science <br> I love volleyball and basketball and from my picture, my doggo Gucci!</p2>
                </div>

            </div>
            
    </body>
</html>

website/templates/form.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width", intital-scale=1.0>
        <title>bro idek</title>

        <link rel = "stylesheet" href="../static/styles/style.css">

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
        integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    </head>
    <body>
      <div class = "container">
        <div class = "navbar">
            <img src="../static/styles/logo.jpeg" class ="logo"> <!-- We add our logo here when we make it -->
            <nav>
                <ul>
                  <li><a href="{{ url_for('auth.gallery') }}">GALLERY</a></li>
                  <li><a href="{{ url_for('auth.aboutUs') }}">ABOUT US</a></li>
                </ul>
            </nav>
            <img src = "../static/styles/menu.png" class ="menu-icon"> <!-- Menu Icon is needed -->
        </div>

        {% with messages = get_flashed_messages(with_categories=true) %} {% if
            messages %} {% for category, message in messages %} {% if category ==
            'noData' %}
            <div class="alert alert-danger alter-dismissable fade show" role="alert">
              {{ message }}
              <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            {% else %}
            <div class="alert alert-success alter-dismissable fade show" role="alert">
              {{ message }}
              <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            {% endif %} {% endfor %} {% endif %} {% endwith %}


        <form method = "POST">
            Business Name: <br><input type="text" name="BusinessName" placeholder = "business name here"><br>
            Bio: <br><input type = "text" name = "Bio" placeholder = "Give a little description of your business (Max 150 characters)"><br>
            Address: <br><input type = "text" name = "Address" placeholder = "(#, Street, City, Postal Code)"><br>
            Photos: <br><input type="file" name = "Photos"><br>
            Business Type: <br> <select name = "BusinessType" id = "BusinessType">                    
              <optgroup label="Types">
                <option value="Choose">Choose One</option>
              <option value="fitness">Fitness</option>
              <option value="pharmaceuticals">Pharmaceuticals</option>
              <option value="jewelry">Jewelry</option>
              <option value="clothing">Clothing</option>
              <option value="Food">Food</option>
              <option value="outdoorServices">Outdoor Services</option>
              <option value="indoorServices">Indoor Services</option>
              <option value="recreation">Recreation</option>
              <option value="technology/electronics">Technology/Electronics</option>
              <option value="entertainment">Entertainment</option>
              <option value="toys">Toys</option>
              <option value="finances/law">Finances/Law</option>
              <option value="other">Other</option>
          </optgroup></select>
          <input type = "submit" value = "Submit">  
          </form>
        
          
    </body>

</html>

website/templates/index.html
```<html> 
    <head>
        <meta name="viewport" content="width=device-width", intital-scale=1.0>
        <title>bro idek</title>

        <link rel = "stylesheet" href="../static/styles/style.css">

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
        integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    </head>
<body>
    <div class = "container">
        <div class = "navbar">
            <img src="../static/styles/logo.jpeg" class ="logo"> <!-- We add our logo here when we make it -->
            <nav>
                <ul>
                    <li><a href="{{ url_for('auth.gallery') }}">GALLERY</a></li>
                    <li><a href="{{ url_for('auth.aboutUs') }}">ABOUT US</a></li>
                </ul>
            </nav>
            <img src = "../static/styles/menu.png" class ="menu-icon"> <!-- Menu Icon is needed -->
        </div>

        <div class ="row">
            <div class = "col">
                <h1>SB Gallery</h1>
                    <p>Welcome to SB Gallery! In our efforts to get local businesses back on track, we created this website so that local businesses can post their "business cards" in our gallery. Feel free to scope around and support the small guys!</p>
            </div>
        </div>

        <div class = "card card1">
            <h5> Tibet Kitchen </h5>
            <p>Cuisine: Tibetan and Himalayan</p>
            <p2>Address: 1544 Queen St. W., Toronto, ON
                M6R 1A6</p2>
        </div>
        <div class = "card card2">
            <h5> Sugo </h5>
            <p>Cuisine: Italian-American</p>
            <p2>Address: 1281 Bloor St. W., Toronto, ON M6H 1N7</p2>
        </div>
        <div class = "card card3">
            <h5> Farm-to-table </h5>
            <p>Cuisine: Farm-to-table</p>
            <p2>Address: 216 Ossington Ave., Toronto, ON M6J 2Z9</p2>
        </div>
        <div class = "card card4">
            <h5> Golden Turtle </h5>
            <p>Cuisine: Vietnamese</p>
            <p2>Address: 125 Ossington Ave., Toronto, ON M6J 2Z2</p2>
        </div>
        <div class = "card card5">
            <h5> Lost & Found </h5>
            <p>Store: Clothing store and coffee shop</p>
            <p2>Address: 44 Ossington Ave, Toronto, ON M6J 2Y7</p2>
        </div>
        <div class = "card card6">
            <h5> Monkey's Paw </h5>
            <p>Store: A shop specializing in rare books</p>
            <p2>Address: 1229 Dundas St W, Toronto, ON M6J 1X6</p2>
        </div>
        <div class = "card card7">
            <h5> Revelo Bikes </h5>
            <p>Store: A builder of better electric bikes</p>
            <p2>Address: 42 Industrial St #108, East York, ON M4G 1Y9</p2>
        </div>
        <div class = "card card8">
            <h5> Snakes Lattes </h5>
            <p>Store: A board game cafe and social place</p>
            <p2>Address: 600 Bloor St W Toronto, ON M6G 1K4</p2>
        </div>
        <div class = "card card9">
            <h5> Steam Whistle </h5>
            <p>Store: A microbrewery that makes only one kind of beer</p>
            <p2>Address: 255 Bremner Blvd, Toronto, ON M5V 3M9</p2>
        </div>

    <!--    <button id ="open">
            Click me please
        </button>

        <div class = "model-container" id="model_container">
            <div class = "model">
                <h2>Models</h2>
                <p>
                    Lorem, ipsum dolor sit amet consectetur adipisicing elit. Porro neque nam voluptatibus, odio, vero, eaque repudiandae explicabo rerum provident quo impedit repellendus saepe ullam ipsum voluptas tenetur veniam. Tempora, quaerat!
                </p>
                <botton id = "close">
                    Close me
                </botton>
            </div>
        </div>
 -->
        <div class = "media"><!--pop up need to go in here-->
            <ul>
                <li><a href="{{url_for('auth.forms')}}"target="_blank"><i class="fa fa-plus"></i></a></li> <!--pop up need to go in here inside the href-->
            </ul>
        </div>
</body>
</html>```